import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
        padding: 10,
    },
    list: {
      padding: 16,
    },
    card: {
        flexDirection: 'row',
        marginBottom: 16,
        backgroundColor: '#fff',
        borderRadius: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    cardInfo: {
        flex: 1,
        padding: 12,
    },
    title: {
        fontSize: 20,
        fontWeight: 'bold',
        marginBottom: 4,
        color: '#333',
    },
    year: {
        fontSize: 16,
        color: '#888',
    },
    ratingContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    rating: {
        fontSize: 16,
        color: '#444',
        marginRight: 8,
    },
    contentContainer: {
        padding: 16,
        backgroundColor: '#fff',
        borderRadius: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    duration: {
        fontSize: 14,
        color: '#888',
    },
    filterBar: {
        padding: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#ddd',
        backgroundColor: '#fff',
        marginBottom: 10,
    },
    filterText: {
        fontSize: 16,
        color: '#333',
    },
    movieList: {
        flex: 1,
        justifyContent: 'center',
    },
    poster: {
        width: 100,
        height: 150,
        borderRadius: 10,
        margin: 10,
    },
    statusContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginBottom: 16,
    },
    statusOption: {
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: '#ddd',
        marginRight: 8,
        marginBottom: 8,
    },
    statusText: {
        color: '#666',
    },
    input_name: {
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 8,
        padding: 12,
        marginBottom: 16,
    },
    input_note: {
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 8,
        padding: 12,
        height: 100,
        textAlignVertical: 'top',
        marginBottom: 16,
    },
    infoRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 16,
    },
    genreContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginBottom: 16,
    },
    genrePill: {
        backgroundColor: '#e6f2ff',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 16,
        marginRight: 8,
        marginBottom: 8,
    },
    genreText: {
        color: '#007bff',
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        marginTop: 16,
        marginBottom: 8,
    },
    addButton: {
        backgroundColor: '#1a1a2e',
        padding: 16,
        borderRadius: 8,
        alignItems: 'center',
    },
    addButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    submitButton: {
        backgroundColor: '#1a1a2e',
        padding: 16,
        borderRadius: 8,
        alignItems: 'center',
        marginTop: 24,
    },
    submitButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    backButton: {
        alignSelf: 'flex-start',
        marginBottom: 5,
        marginRight: 10,
        flexDirection: 'row',
    },
    movieResultItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 10,
        marginRight: 10,
        borderWidth: 1,
        borderColor: '#ddd',
        borderRadius: 5,
    },
    selectedMovieItem: {
        backgroundColor: '#e6f2ff',
        borderColor: '#007bff',
    },
    movieResultTitle: {
        marginRight: 5,
        fontWeight: 'bold',
    },
    movieResultYear: {
        color: '#666',
    },
    searchResultsContainer: {
        marginVertical: 10,
        maxHeight: 100,
    },
    movieInfo: {
        marginVertical: 10,
        padding: 10,
        backgroundColor: '#f0f0f0',
        borderRadius: 5,
    }, 
    statusSelected: {
        backgroundColor: '#1a1a2e',
        borderColor: '#1a1a2e',
    },
    statusTextSelected: {
        color: '#fff',
    },
    modalView: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalText: {
        fontSize: 18,
        color: '#fff',
        marginBottom: 20,
    },
    footer: { 
        padding: 10, 
        backgroundColor: '#1a1a2e', 
        alignItems: 'center', 
        justifyContent: 'center' 
    },
    footerText: { 
        color: '#fff', 
        fontSize: 16 
    },
    status: { 
        color: '#fff',
        fontSize: 14, 
        marginTop: 6,
        paddingVertical: 4,
        paddingHorizontal: 12,
        borderRadius: 20,
        alignSelf: 'flex-start',
    },
    header: { 
        padding: 10,
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 20, 
    },
    noDataText: { 
        fontSize: 18, 
        textAlign: 'center', 
        marginTop: 20 
    },
    watchListItem: {
        flexDirection: 'row',
        backgroundColor: '#fff',
        padding: 10,
        borderRadius: 8,
        height: 150,
        marginBottom: 10,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    watchListPoster: { 
        width: 80,
        height: 120,
        borderRadius: 8,
        marginRight: 10,
    },
    movieInfo: {
        flex: 1,
        justifyContent: 'center',
    },
    errorText: {
        color: 'red',
        fontSize: 16,
        textAlign: 'center',
    },
    label: {
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 8,
        color: '#333',
    },
    scrollView: {
        flex: 1,
    },
    backButtonText: {
        color: '#1a1a2e',
        fontSize: 16,
    },
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
    },
    modalContent: {
        backgroundColor: '#fff',
        padding: 20,
        borderRadius: 10,
        alignItems: 'center',
    },
    modalText: {
        fontSize: 16,
        color: '#333',
    },
    
    headerTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#fff',
    },
    form: {
        backgroundColor: '#fff',
        padding: 16,
        borderRadius: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    backText: {
        color: '#1a1a2e',
        fontSize: 16,
        paddingLeft: 5,
    },
    cast: {
        fontSize: 16,
        color: '#666',
        marginBottom: 16,
    },
    saveButton: {
        backgroundColor: '#1a1a2e',
        padding: 10,
        borderRadius: 5,
        marginTop: 20,
    },
    saveButtonText: {
        color: '#fff',
        fontSize: 16,
    },
    changeStatusButton: {
        backgroundColor: '#1a1a2e',
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 25,
        alignItems: 'center',
        marginTop: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 5,
    },
    changeStatusButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
    filterBar: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
        padding: 10,
        backgroundColor: '#fff',
        borderRadius: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    searchBar: {
        flex: 1,
        height: 40,
        borderColor: '#ccc',
        borderWidth: 1,
        borderRadius: 5,
        paddingLeft: 10,
        backgroundColor: '#fff',
    },
    sortPicker: {
        width: '100%',
        height: 50,
        marginLeft: 10,
        flex: 1
    },
});

export default styles;